# Generated by Django 5.2.6 on 2025-09-30 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso_energia', models.BooleanField(blank=None, null=None)),
                ('power', models.BooleanField(blank=None, null=None)),
                ('title', models.CharField(blank=None, max_length=100, null=None)),
                ('local', models.CharField(blank=None, max_length=100, null=None)),
                ('definicao', models.CharField(blank=None, max_length=100, null=None)),
                ('tempo_exec', models.CharField(blank=None, max_length=10, null=None)),
                ('uso_ener', models.CharField(blank=None, max_length=10, null=None)),
                ('potencia_atual', models.CharField(blank=None, max_length=10, null=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
