# Generated by Django 5.2.6 on 2025-09-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='definicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='potencia_atual',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='power',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tempo_exec',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='uso_ener',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='uso_energia',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
